title: Driven By Values
description: Personal Webpage for Career journey
show_downloads: false
google_analytics:
theme: jekyll-theme-architect

# Plugins
plugins:
  - jekyll-seo-tag

# Enable plugins
gems:
  - jekyll-seo-tag

# Plugin settings
year_pages:
  enabled: true
  years:
    start: 1998
    end: 2025

# Include all files in the _pages directory
include:
  - _pages

nav_links:
  - label: Resume
    url: /
  - label: Timeline
    url: /timeline/
  - label: Skills
    url: /skills/
  - label: Years
    url: /years/
  - label: Contact
    url: /#contact

formspree_id: your-form-id

# Set default front matter defaults
defaults:
  - scope:
      path: "_pages"
    values:
      layout: "default"
      permalink: /:title/

# Exclude files from being processed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
